nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'

  cpu:
    - 'current'
    - 'x86'
    - 'x64'
    - 'arm64'
    - 'ia32'
