nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'

  cpu:
    - 'current'
    - 'x86'
    - 'x64'
    - 'arm64'
    - 'ia32'

packageExtensions:
  # This fixes an issue with docsearch's peer dependencies
  # https://github.com/algolia/docsearch/issues/1272
  '@docsearch/react@*':
    peerDependenciesMeta:
      '@algolia/client-search':
        optional: true
      '@types/react':
        optional: true
      'react':
        optional: true
      'react-dom':
        optional: true
