blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/sister-software/keywork/discussions/new
    about: Ask the community for help on our GitHub Discussions board
