name: Site Deployment

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.4
      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Build Modules
        run: |
          yarn build
        env:
          NODE_ENV: production
          CI: true

      - name: Generate docs
        run: |
          yarn docs:generate
        env:
          NODE_ENV: production
          CI: true

      - name: Build site
        run: |
          yarn site:build
        env:
          NODE_ENV: production
          CI: true

      - name: Archive doc site artifacts
        uses: actions/upload-artifact@v3
        with:
          name: keywork-site
          path: site/build
          retention-days: 5

      - name: Deploy Site
        run: |
          yarn site:deploy site/build
        env:
          NODE_ENV: production
          CI: true
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
