name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.4
      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Build Modules
        run: |
          yarn build
        env:
          NODE_ENV: production

      - name: Run tests
        run: yarn workspace keywork run test

      - name: Generate lcov
        run: yarn workspace keywork run test:coverage > cov.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: cov.lcov

      - name: Build site
        run: |
          yarn site:build
        env:
          NODE_ENV: production

      - name: Archive Keywork artifacts
        uses: actions/upload-artifact@v3
        with:
          name: keywork-dist
          path: dist
          retention-days: 5

      - name: Archive doc site artifacts
        uses: actions/upload-artifact@v3
        with:
          name: keywork-site
          path: site/build
          retention-days: 5
