name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.4
      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Run tests
        run: yarn workspace @keywork/modules run test

      - name: Generate lcov
        run: yarn workspace @keywork/modules run test:coverage > cov.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: cov.lcov

      - name: Build application
        run: |
          yarn build
        env:
          NODE_ENV: production

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-full
          path: |
            dist
          retention-days: 5
